startpuml foco

class Usuario 

class Foco{
- EstadoFoco estado 
+ Encender()
+ Apagar()
+ LeerEstado() : EstadoFoco
}


class EstadoFoco 
class Seriefocos{
    - Foco focos [10]
    + MostrarFocos()
    + EncenderFocos()
    + MostrarFocos() 
}

Usuario o--  Foco
Foco *-- EstadoFoco  
EstadoFoco --|> Boleano 
@enduml